<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="icon" href="{{env('APP_URL')}}/img/logo.png">
    <link rel="stylesheet" href="{{env('APP_URL')}}/assets/css/style.css">
    <title>Ecom Buyer</title>
    <style>
.termhead{
    display: flex;
    justify-content: center;
    align-items: flex-start;
    flex-direction: column;
    color: #fff;
}
.termhead h1{
    font-size: 55px;
}
.hiddenimg{
    display: flex;
    justify-content: center;
    align-items: flex-end;
}
.hiddenimg img{
 width: 100%;
}
.box-container{
    padding-top: 100px;
    padding-bottom: 80px;
}
.bread{
    display: flex;
    align-items: center;
    flex-direction: row;
    font-size: 18px;
}
.bread a{
    color: #a5a4a4;
    text-decoration: none;    
}
.termcontent h3{
    color: var(--main-color);
    font-size: 35px;
    font-weight: 600
}
.termcontent p, .termcontent li{
    color: var(--sec-color);
    line-height: 30px;
}
@media only screen and (max-width: 767px){
    .termhead{
        margin-bottom: 40px;
    }
}

    </style>
</head>

<body>
    <a href="#" class="scrollToTop active"><i class="fas fa-angle-double-up"></i></a>
{{-- navbar --}}
    <nav class="navbar" id="navbar">
        <div class="navbar-container container">
            <input type="checkbox" name="" id="">
            <div class="hamburger-lines">
                <span class="line line1"></span>
                <span class="line line2"></span>
                <span class="line line3"></span>
            </div>
            <ul class="menu-items">
                <li><a href="{{route('user.index')}}">Home</a></li>
                <li><a href="{{route('user.services')}}">Services</a></li>
                <li><a href="{{route('user.process')}}">Processing</a></li>
                <li><a href="{{route('user.about')}}">About us</a></li>               
                <li><a href="{{route('user.contact')}}">Contact</a></li>               
            </ul>
            <h1 class="logo">Ecom Buyer</h1>
        </div>
    </nav>
    <div class="container-fluid" style="margin-top: 90px;background:var(--main-color);">
        <div class="container box-container">
            <div class="row">
                <div class="col-lg-7 col-md-7 col-12 termhead">
                    <h1 data-aos="fade-left" data-aos-delay="100">Privacy Policy</h1>
                    <div data-aos="fade-left" class="bread" data-aos-delay="400"><a href="{{route('user.index')}}">Home</a><span class="mx-2">/</span><span>Privacy Policy</span></div>
                </div>
                <div class="col-lg-5 col-md-5 col-12 hiddenimg">
                    <img data-aos="fade-up" src="{{env('APP_URL')}}/assets/img/privacy-policy.png" alt="">
                </div>
            </div>
            
        </div>
    </div>
    <div class="container mt-5">
        <div class="col-xl-12 termcontent">            
            <p class="mb-3" data-aos="fade-up">Ecom Buyer PVT. LTD. (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Ecom Buyer PVT. LTD.</p>
            <p class="mb-3" data-aos="fade-up">This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, Ecom Buyer PVT. LTD.. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.</p>
            <h3 class="mb-3">Definitions and key terms</h3>
            <p class="mb-3" data-aos="fade-up">To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</p>
            <ul data-aos="fade-up">
                <li>Cookie: Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.</li>
                <li>Company: When this policy mentions “Company,” “we,” “us,” or “our,” it refers to Ecom Buyer PVT. LTD., (FF-48Omaxe Arcade, Golf Link-I, Alpha Greater Noida, Gautam Buddha Nagar, Maicha, Uttar Pradesh, India, 201310), that is responsible for your information under this Privacy Policy.</li>
                <li>Country: Where Ecom Buyer PVT. LTD. or the owners/founders of Ecom Buyer PVT. LTD. are based, in this case is India</li>
                <li>Customer: Refers to the company, organization or person that signs up to use the Ecom Buyer PVT. LTD. Service to manage the relationships with your consumers or service users.</li>
                <li>Device: Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Ecom Buyer PVT. LTD. and use the services.</li>
                <li>IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                <li>Personnel: Refers to those individuals who are employed by Ecom Buyer PVT. LTD. or are under contract to perform a service on behalf of one of the parties.</li>
                <li>Personal Data: Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                <li>Service: Refers to the service provided by Ecom Buyer PVT. LTD. as described in the relative terms (if available) and on this platform.</li>
                <li>Third-party service: Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                <li>Website: Ecom Buyer PVT. LTD. site, which can be accessed via this URL: https://ecombuyer.in/</li>
                <li>You: A person or entity that is registered with Ecom Buyer PVT. LTD. to use the Services.
                </li>
            </ul>
            <h3 class="mb-3"  data-aos="fade-up">Information automatically collected</h3>
            <p class="mb-3" data-aos="fade-up">There is some information like your Internet Protocol (IP) address and/or browser and device characteristics — is collected automatically when you visit our platform. This information may be used to connect your computer to the Internet. Other information collected automatically could be a login, e-mail address, password, computer and connection information such as browser plug-in types and versions and time zone setting, operating systems and platforms, purchase history, (we sometimes aggregate with similar information from other Users), the full Uniform Resource Locator (URL) clickstream to, through and from our Website that may include date and time; cookie number; parts of the site you viewed or searched for; and the phone number you used to call our Customer Services. We may also use browser data such as cookies, Flash cookies (also known as Flash Local Shared Objects) or similar data on certain parts of our Website for fraud prevention and other purposes. During your visits, we may use software tools such as JavaScript to measure and collect session information including page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page. We may also collect technical information to help us identify your device for fraud prevention and diagnostic purposes.</p>
            <p class="mb-3" data-aos="fade-up">We automatically collect certain information when you visit, use or navigate the platform. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about who and when you use our and other technical information. This information is primarily needed to maintain the security and operation of our platform, and for our internal analytics and reporting purposes.</p>
            <h3 class="mb-3">Personnel</h3>
            <p class="mb-3" data-aos="fade-up">If you are a Ecom Buyer PVT. LTD. worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.</p>
            <p class="mb-3" data-aos="fade-up">You may contact us in order to (1) Update or correct your information, (2) Change your preferences with respect to communications and other information you receive from us, or (3) Receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.
            </p>
            <h3 class="mb-3">Sale of Business</h3>
            <p class="mb-3" data-aos="fade-up">We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of Ecom Buyer PVT. LTD. or any of its Corporate Affiliates (as defined herein), or that portion of Ecom Buyer PVT. LTD. or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.</p>
            <h3 class="mb-3">Affiliates</h3>
            <p class="mb-3" data-aos="fade-up">We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, “Corporate Affiliate” means any person or entity which directly or indirectly controls, is controlled by or is under common control with Ecom Buyer PVT. LTD., whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.</p>
            <h3 class="mb-3">Governing Law</h3>
            <p class="mb-3" data-aos="fade-up">This Privacy Policy is governed by the laws of India without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.</p>
            <p class="mb-3" data-aos="fade-up">The laws of India, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.</p>
            <p class="mb-3" data-aos="fade-up">By using Ecom Buyer PVT. LTD. or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.
            </p>
            <h3 class="mb-3">Your Consent</h3>
            <p class="mb-3" data-aos="fade-up">We’ve updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it’s being used. By using our Ecom Buyer PVT. LTD., registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.</p>
            <h3 class="mb-3">Links to Other Websites</h3>
            <p class="mb-3" data-aos="fade-up">This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by Ecom Buyer PVT. LTD.. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.</p>
            <h3 class="mb-3">Cookies</h3>
            <p class="mb-3" data-aos="fade-up">Ecom Buyer PVT. LTD. uses “Cookies” to identify the areas of our website that you have visited. A cookie is a small piece of data stored on your computer or mobile device by your web browser. We use cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.</p>

            <h3 class="mb-3" >Blocking and disabling cookies and similar technologies</h3>
            <p class="mb-3" data-aos="fade-up">Wherever you’re located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser’s help menu for more information.
            </p>
            <h3 class="mb-3">Kids’ Privacy</h3>
            <p class="mb-3" data-aos="fade-up">We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
            <h3 class="mb-3">Changes To Our Privacy Policy</h3>
            <p class="mb-3" data-aos="fade-up">We may change our Services and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.</p>
            <h3 class="mb-3">Third-Party Services</h3>
            <p class="mb-3" data-aos="fade-up">We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (“Third-Party Services”).</p>
            <p class="mb-3" data-aos="fade-up">You acknowledge and agree that Ecom Buyer PVT. LTD. shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Ecom Buyer PVT. LTD. does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</p>
             <p class="mb-3" data-aos="fade-up">Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties terms and conditions.
            </p>
            <h3 class="mb-3">Tracking Technologies</h3>
            <ul>
                <li>Google Maps API : Google Maps API is a robust tool that can be used to create a custom map, a searchable map, check-in functions, display live data syncing with location, plan routes, or create a mashup just to name a few. Google Maps API may collect information from You and from Your Device for security purposes. Google Maps API collects information that is held in accordance with its Privacy Policy</li>
                <li>Cookies: We use cookies to enhance the performance and functionality of our but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the as we would not be able to remember that you had logged in previously.</li>
                <li>Sessions: uses “Sessions” to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.</li>
            </ul>
            <h3 class="mb-3">Information about General Data Protection Regulation (GDPR)</h3>
            <p class="mb-3" data-aos="fade-up">We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how and why this data is collected, and how we maintain this data under protection from being replicated or used in the wrong way.</p>
            <h3 class="mb-3">What is GDPR?</h3>
            <p class="mb-3" data-aos="fade-up">GDPR is an EU-wide privacy and data protection law that regulates how EU residents’ data is protected by companies and enhances the control the EU residents have over their personal data.</p>
            <p class="mb-3" data-aos="fade-up">The GDPR is relevant to any globally operating company and not just the EU-based businesses and EU residents. Our customers’ data is important irrespective of where they are located, which is why we have implemented GDPR controls as our baseline standard for all our operations worldwide.</p>
            <h3 class="mb-3">What is personal data?</h3>
            <p class="mb-3" data-aos="fade-up">Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person’s name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical addresses, sexual orientation, and ethnicity.</p>
            <p class="mb-3" data-aos="fade-up">The Data Protection Principles include requirements such as:</p>
            <ul>
                <li>Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</li>
                <li>Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need personal data when they collect it.</li>
                <li>Personal data should be held no longer than necessary to fulfil its purpose.</li>
                <li>People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</li>
            </ul>
            <h3 class="mb-3">Why is GDPR important?</h3>
            <p class="mb-3" data-aos="fade-up">GDPR adds some new requirements regarding how companies should protect individuals’ personal data that they collect and process. It also raises the stakes for compliance by increasing enforcement and imposing greater fines for breach. Beyond these facts, it’s simply the right thing to do. At Ecom Buyer PVT. LTD. We strongly believe that your data privacy is very important and we already have solid security and privacy practices in place that go beyond the requirements of this new regulation.</p>
            <h3 class="mb-3">Individual Data Subject’s Rights – Data Access, Portability and Deletion</h3>
            <p class="mb-3" data-aos="fade-up">We are committed to helping our customers meet the data subject rights requirements of GDPR. Ecom Buyer PVT. LTD. processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.</p>
            <p class="mb-3" data-aos="fade-up">We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update, retrieve and remove personal data. We got you! We’ve been set up as self-service from the start and have always given you access to your data and your customer’s data. Our customer support team is here for you to answer any questions you might have about working with the API.</p>
            <h3 class="mb-3">Contact Us</h3>
            <p class="mb-3" data-aos="fade-up">Don’t hesitate to contact us if you have any questions.</p>
            <p class="mb-3" data-aos="fade-up">Via Email: info@ecombuyer.com</p>
        </div>
    </div>
  
    <footer style="background: var(--sec-color)" class="pt-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12 d-flex justify-content-start align-items-start">
                    <img src="{{env('APP_URL')}}/assets/img/nobglogo.png" class="mb-2" alt=""><h1 class="text-white mx-2">Ecom Buyer</h1>
                </div>
                <div class="col-lg-12 col-md-12 col-12 mb-4 col-12 d-flex justify-content-start align-items-center">
                    <ul style="display:flex;flex-direction:row">
                        <li>
                           <a href=""> About us</a>
                        </li>
                        <li>
                            <a href="{{route('user.terms')}}">Terms</a>
                        </li>
                        <li>
                            <a href="{{route('user.privacy')}}">Privacy</a>
                        </li>
                        <li>
                            <a href="">Contact</a>
                         </li>
                    </ul>
                </div>
                <hr style="color: #fff">
                <div class="d-flex justify-content-center align-items-center flex-wrap" class="pb-5">
                    <p style="color: white; margin-top:1rem; margin-bottom: 40px">Copyright © 2024 ECOM BUYER PVT. LTD. </p>
                </div>  
            </div>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            AOS.init({
                duration: 1000, 
                easing: 'ease-in-out', 
                once: true 
            });
        });
    </script>
<script>
    // JavaScript to change navbar background on scroll
    window.addEventListener('scroll', function() {
            var navbar = document.getElementById('navbar');
            if (window.scrollY > 0) {
                navbar.style.backgroundColor = '#fff';     
                navbar.style.boxShadow = '2px 3.464px 24px 0px rgba(106, 105, 194, 0.25)';     
            } else {
                navbar.style.backgroundColor = 'transparent'; 
                navbar.style.boxShadow = 'none'; 
            }
        });
</script>
<script>
     // Scroll Top
     var ScrollTop = $(".scrollToTop");
    $(window).on('scroll', function () {
      if ($(this).scrollTop() < 500) {
        ScrollTop.removeClass("active");
      } else {
        ScrollTop.addClass("active");
      }
    });
    $('.scrollToTop').on('click', function () {
      $('html, body').animate({
        scrollTop: 0
      }, 500);
      return false;
    });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wow.js/1.1.2/wow.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-GKwjsm0PHG4lJ6bDhUWunlKVm5+3O/qwBhQmBou/5A3rHx2R3YwDt40FQu59kuA4" crossorigin="anonymous"></script>
</body>
</html>